### ISSUE TITLE
Using LARVIO with realsense d435i

### ISSUE THREAD

**Issue by Filea** [PetWorm/LARVIO#3]
Hello, 

I would like to know if it is possible to run this algorithm with the realsense d435i. 
I tried it but the results are far from being good. May be is something wrong with the configuration that I'm using...

Do you have any configuration for this camera like you have for the mynteye?

Best, 
Filipe

**Comment by PetWorm** [comment]
Hi, sadly I have not yet tried LARVIO on D435i. But I think running with any hardware synchronized VI sensors would not be a problem. 

The information you provided are too few, but still there are some tips may help you:
1. Make sure you calibrate the intrinsic parameter of camera and extrinsic parameter between camera and IMU carefully, and change those parameters accordingly in the config file.
2. Check if you turn on the IR, if you did, try turn it off, since it would affect the feature extraction.

Please provide more information and I will see if I can help.

**Comment by ebigMan** [comment]
Hello @PetWorm :
I have been trying to use Larvio to locate the bag data recorded by d435i recently. The recording process was carried out on a car with a speed of 30-40km/h. I found that the trajectory would drift significantly back and forth, even left and right, when turning or waiting for red street lights. However, when using the hardware parameters provided in the code and the Euroc dataset for testing, I feel that even if there is a rotation trajectory, there will be no abnormalities. What is the reason for this? Is it because my camera's internal and external parameter calibration is not accurate enough?

Best wish!
